### ISSUE TITLE
Bug: regression on the current master

### ISSUE THREAD

**Issue by gdassori** [henrycunh/geppeto#17]
![image](https://user-images.githubusercontent.com/5659270/229346892-10e85033-3027-4b79-a765-fb423f686c6f.png)

```
[nuxt] [request error] [unhandled] [500] Cannot set properties of undefined (setting 'value')
  at ./chunks/app/server.mjs:772:18  
  at fn (./chunks/app/server.mjs:147:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)  
  at callWithNuxt (./chunks/app/server.mjs:149:23)  
  at applyPlugin (./chunks/app/server.mjs:118:39)  
  at applyPlugins (./chunks/app/server.mjs:127:11)  
  at async createNuxtAppServer (./chunks/app/server.mjs:1046:7)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)  
  at async ./chunks/handlers/renderer.mjs:384:21  
  at async ./chunks/handlers/renderer.mjs:26:22
  ```

**Comment by henrycunh** [comment]
oh oh, on it!

**Comment by gdassori** [comment]
Hi @henrycunh, it wasn't on the page you mentioned, but on the home, and it is still happening :-(.

![image](https://user-images.githubusercontent.com/5659270/229356443-f71dc65f-bde3-4321-b300-6a3363eb9aba.png)

I'm going to give you the URL of my installation on a Twitter DM, which could be helpful maybe.

**Comment by henrycunh** [comment]
That's weird! It's working here.
![image](https://user-images.githubusercontent.com/8951736/229357639-40126ad5-2d34-4ed1-be1c-2eb906205100.png)

**Comment by henrycunh** [comment]
You're using Chrome? Can you show me the stack trace on the server-side?

**Comment by gdassori** [comment]
Yes, Chrome is here.
This is the log from vercel (500 server error):
```
[nuxt] [request error] [unhandled] [500] Cannot set properties of undefined (setting 'value')
  at ./chunks/app/server.mjs:772:18  
  at fn (./chunks/app/server.mjs:147:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)  
  at callWithNuxt (./chunks/app/server.mjs:149:23)  
  at applyPlugin (./chunks/app/server.mjs:118:39)  
  at applyPlugins (./chunks/app/server.mjs:127:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async createNuxtAppServer (./chunks/app/server.mjs:1046:7)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)  
  at async ./chunks/handlers/renderer.mjs:384:21
```

**Comment by henrycunh** [comment]
Perfect! Just found the bug :]

**Comment by gdassori** [comment]
Fix confirmed here, thank you @henrycunh  :+1: :+1: :+1:
